### ISSUE TITLE
Digital Signature Timeline?

### ISSUE THREAD

**Issue by goldcoders** [ciur/papermerge#103]
Just wondering when you would add this feature ,

I could try to help but my skills on python and django is not on par with you lol...

im quite familiar with gnupg but

Dont know if you will use gnupg for this one, i think python has wrapper on it python-gnupg

**Comment by ciur** [comment]
@goldcoders, I don't have plans for digital signatures yet. But if it would be added (and it will be added at some point) - it must/will be only added as plugin (django app).

It is so because, digital signatures (and many other similar features, e.g. document workflows) are not used by everybody.
So it makes sense only to add it/them as plugin/django app
