### ISSUE TITLE
Verify / Modify Result Text files

### ISSUE THREAD

**Issue by goldcoders** [ciur/papermerge#104]
Sometimes the extracted text dont match , is there a way we can verify in the UI and edit the output to make it more concise , 
I have experience converting image or pdf to text with tessarct command  not getting 100% correct match... sometimes...

it would be handy , since we already have the file and output text save on 
./media/results/**/*.txt

maybe we can add on the UI a way to verify the output text and change it if theres Discrepancy

**Comment by ciur** [comment]
It is not so easy at it looks like. The problem is that txt files (and  hocr files as well) are moved around. Try to upload a pdf with couple of pages and (after OCR is ready) try to reorder pages and you will understand what I mean.

On file level documents are versioned. Every time you reorder/cut/paste pages - a new version is created. And inside that version
.txt are moved/copied.
