### ISSUE TITLE
Have you considered a Move to action?

### ISSUE THREAD

**Issue by ciur** [ciur/papermerge#121]
Have you considered a Move to action?
- Select items
- click Move To
- pops up a folder browser allowing you to select the destination

Feels a bit more intuitive to me, especially if you are filing a large number of things from the inbox.
Drag and drop is less useful when you have multiple levels of folders.

**Comment by ciur** [comment]
Above comment is my copy/paste from another ticket's feedback.

**Comment by Ionshard** [comment]
Pretty pretty please! I just installed Papermerge on my local server and based on how painful it is to organize the Inbox during my trial use of importing just 100 documents I am tempted to look elsewhere but I really like a lot of the other features!

Maybe I am doing something wrong but the here is what typically happens when attempting to organize my Inbox (except of course for automates which are amazing and part of why I want to stick with Papermerge) is the following:

- Go to Inbox (+1 Page Load)
- Right click a document without selecting it and then curse at the greyed out Cut button! (You shouldn't need to select a document before interacting with it via the Context menu)
- Miss the tiny select checkbox, accidentally clicking the document taking me into the document view (+1 Page Load)
- Click back (+1 Page Load)
- Finally click the tiny select checkbox on the document.
- Right click the document and select Cut
- Go to the documents page (+1 Page Load)
- Navigate down the tree to my desired folder
- Right click and select Paste

Now I know some of these steps are mistakes and cheeky complaints, but they are genuine mistakes I have made many many times since trying to get used to this software. Ultimately involving 2-4 page loads per document I move.

What I wish the way to organize my files went:

- Load Inbox page (+1 Page Load)
- Right click document and select Move
- A modal or light box pops up with my directory structure where I can select a new location
- Click a final "Move" button and the document moves there and I am still on the Inbox page

Since I never leave the Inbox page this means I can organize my entire Inbox with just 1 single page load instead of 2 page loads per document.

This is exactly what my current solution for managing my scans does which is pCloud (which is like a Google Drive alternative) so I have recorded it's use so hopefully you can see how useful such a move functionality would be.

![pCloud Move](https://user-images.githubusercontent.com/86419/124156622-d846c200-da65-11eb-9f61-24946cc776bb.gif)

Now pCloud has no OCR, barebones previews, no page management, garbage search ... so obviously Papermerge is functionally superior in almost every way (once the documents are stable) but I do miss that ease of use in working with new documents!

Now I am aware that it's not just a couple lines of code to implement this and you're basically doing a lot of this in your spare time so I'd be happy to put a bounty of some kind on this enhancement request if that's something you are willing to allow. It's one thing to come on the internet and complain about this completely free software doesn't do the thing I want and I don't want to be that person.

**Comment by ciur** [comment]
Hi @Ionshard, thank you for your detailed feedback. 
I know that cutting/pasting documents/pages is a painful experience as it involves too many redundant steps.
In Papermerge 2.1 (which is in development right now) I addressed this issues by... providing dual panel document browser; this means that basically you could open in one panel the destination folder/document and drag/drop document/pages from another panel. It is really cool feat.  I promise! 
See below gif for a short preview (this is very early preview I as I am still working on this feature):

![dual-panel-feature-preview](https://user-images.githubusercontent.com/24827601/124185991-f3dcb780-dabb-11eb-8c21-60863712d45b.gif)

**Comment by Ionshard** [comment]
That is a much more powerful solution to this problem, that solves my issue and probably many more. That is a tantalizing preview and I am definitely looking forward to the next release now!

**Comment by ciur** [comment]
@Ionshard 
Dual panel mode landed in 2.1. Here is a quick demo of moving some documents from Inbox folder:
![easy-move-of-documents](https://user-images.githubusercontent.com/24827601/183253845-ae687711-b540-4cd8-aa6c-33cdc3485c54.gif)
