### ISSUE TITLE
two dockerfiles?

### ISSUE THREAD

**Issue by georgkrause** [ciur/papermerge#122]
I am currently building arm64 images for my docker swarm and I am wondering why there is a directory `1.2` and `1.4` in the repository. Isn't versioning a task of git? I would pledge for removing the 1.2 and simplifying the repository structure.

**Comment by ciur** [comment]
> why there is a directory 1.2
It is there for compatibility. Because there were significant changes between 1.2 and 1.4 (application changed a lot, docker images were changed a lot) I though it is a good idea to keep 1.2 version around for next couple of versions. Maybe there will be people using it.

>  Isn't versioning a task of git?

yes, it is! And I absolutely agree that it is redundant and maybe confusing to have 1.2 and 1.4. However, not everybody will figure out how to checkout at version 1.2. Let it still be there for couple of more versions and then I will remove docker/1.2/ folder.

**Comment by georgkrause** [comment]
Alright, this is a plan. Maybe it would be good to somehow mark the 1.2 version as deprecated. Anyway, I close this since my question is answered. Thank you!

**Comment by ciur** [comment]
@georgkrause,

by the way, there is a [Papermerge docker image provided by linuxserver.io](https://fleet.linuxserver.io/image?name=linuxserver/papermerge). I checked their image - they did fantastic work! They managed to wrap both worker + main app in a single docker image. It is an excellent alternative to docker images provided by me. You need to keep in mind that I am by far not a docker specialist.
