### ISSUE TITLE
Base OS for Docker image

### ISSUE THREAD

**Issue by georgkrause** [ciur/papermerge#123]
Currently the docker image is based on Ubuntu which makes it bloated and big. Its much better to create slim images based on some much more minimal, eg alpine linux. Would you except a switch?

**Comment by georgkrause** [comment]
I am not really suggesting using alpine linux, I just want to start a discussion if there might be the option to use something more minimal. There are some issues with python and alpine, which maybe is too much effort. But there are some other options like debian minimal or whatever.

**Comment by ciur** [comment]
Hi @georgkrause,

I have nothing against alpine base image and I think it is a good idea to have Papermerge docker image running over the minimal linux image.
However there is one very important point to keep in mind.
Making Papermerge run over Alpine is not a trivial task. This is because Papermerge depends on many 3rd party applications like tesseract, imagemagick, poppler let it alone python with some of its dependencies shipped as compiled binary libs (e.g. lxml).
Now, alpine linux, in order to be as small as possible does not ship with glibc, instead is based on [musl](https://en.wikipedia.org/wiki/Musl). **This means that all binaries compiled against glibc - need to be recompiled/adjusted/tuned with musl.**

I am not curagious enough to try that sort of adventure :)). Plus I am not a system programmer - means I am not familiar with linux system, its ABI, system calls etc.

That being said, if somewhere out there is willing to go over that couragious act - am will gladly help as much as I can :), but doing that alpine based image myself is far beyond my skills.

**Comment by georgkrause** [comment]
Well, thanks for the open words!

I know this is not something which is done in like 5 Minutes. But the current image is not suitable for productive use from my point of view and I want to setup Papermerge so I need to do this anyway. I think the best place for such a Dockerfile would be directly in the repository. 

I know there are some dependencies. But lets see:

* tesseract is available as package: https://pkgs.alpinelinux.org/package/v3.12/community/x86_64/tesseract-ocr
* py3-lxml is available: https://pkgs.alpinelinux.org/package/v3.12/community/mips64/py3-lxml
* imagemagick is there: https://pkgs.alpinelinux.org/package/v3.12/community/x86_64/imagemagick
* poppler is available prebuilt, too: https://pkgs.alpinelinux.org/package/v3.12/main/x86_64/poppler

I am aware that alpine ships with glibc and this was a problem for python some time ago but there are a lot of Alpine based Docker-Images for Python-Applications available and a huge amount of issues is fixed.

All this is no guarantee to make it work, but its worth a try from my point of view. And I want to try.

Now, the question is: Do you want to have something as part of papermerge (which would be the way to go from my pov) or should I develop it somewhere else.

By the way: We still can keep the current docker-files since it seems to be well suited for development, although it might be obsolete later when the alpine image is stable.

I would use the image in production even if its not rock solid yet so we have a good test field.

**Comment by ciur** [comment]
> Do you want to have something as part of papermerge (which would be the way to go from my pov) or should I develop it somewhere else.


I would like a separate repo. It would be great to have similarly how linuxserver.io guys did - they trigger a new docker image build every time there is a new tag created - very smart!

I really like [linuxserver.io approach.](https://github.com/linuxserver/docker-papermerge). They have an ubuntu based arm docker image as well.

By the way, I was asked about alpine based image several times. I am sure if you manage to build one, it will be very popular.

> All this is no guarantee to make it work, but its worth a try from my point of view. And I want to try.

Great ! fingers crossed :crossed_fingers:  :grin:

**Comment by georgkrause** [comment]
Can you explain why you don't want the Dockerfile in this repository? From my point of view its the best to support docker directly. 

If you are against, we can close this issue and I am going to create this Dockerfile.

**Comment by ciur** [comment]
There is one dockerfile in this repository.
I don't see the point to recreate (replace it, add alternative next to) it just because it will be based on other base image.
If you like to create yet another docker image create it in different repo and I will gladly update documentation with a reference to your alternative image.
