### ISSUE TITLE
Django errors in docker image

### ISSUE THREAD

**Issue by technic88** [ciur/papermerge#138]
**Bug Description**
Server shows "Internal Server Error" after deployed via Docker. Logs shows errors with django. 

**Expected behavior**
Papermerge site should show.

**Do you Papermerge via Docker Image ?**
Using linuxserver/papermerge

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser: Firefox, Chrome
 - Papermerge Version 1.4.3

Attached Log: [docker-papermerge-log.txt](https://github.com/ciur/papermerge/files/5278237/docker-papermerge-log.txt)

**Comment by ciur** [comment]
Hi @technic88,

It is just now that I realize that it is not correct to open linuxserver.io/papermerge docker related issues here. The reason is that linuxserver.io image is not maintained by me!

I will correct "bug template" to mention that info. 
Please [open linuxserver.io docker image related issues at their issue tracker.](https://github.com/linuxserver/docker-papermerge/issues)
