### ISSUE TITLE
Automatically sort by alphabet - feature request...

### ISSUE THREAD

**Issue by fumunda** [ciur/papermerge#15]
Me again.

I was curious if you could add a default setting to sort everything alphabetically automatically.  I know we have the option to sort that way, but the default sorting is in whatever order you added folders or files.

**Comment by ciur** [comment]
It is fairly easy to do it.

Long story short, I think it is an excellent feature - with the difference that there will be no "option". **Instead application will just remember the last state.**

For longer version read below :)  

Instead of adding a setting or configuration of this feature, I think it would be a better idea to save the last state. So that if you sorted last time by "sort by date - ascending", all subsequent displays in same (or other) folders will be with "sort by date - ascending".
This way you will still have to chose preferred sorting type - but only once.
If you would be more interested in "sort by date - descending", just sort it that way once, and all subsequent displays will be with "sort by date - 

In preferences there is an option to save view as "list" or "grid".  I think this option is redundant. Similar way to sorting, application just needs to remember the last state the user used.

I will take care of this soon.

**Comment by fumunda** [comment]
I like that idea. I can set it how i want and it will remember.  Sounds good! 

Thanks again!

**Comment by ciur** [comment]
I fixed the issue. 
You'll need to use latest papermerge docker image tagged 1.2.2. 
Also, make sure you force refresh browser page so that it will not use cached version of latest javascript file.

**Comment by fumunda** [comment]
Awesome thanks!  I will update and let you know how things go.

**Comment by fumunda** [comment]
Worked great.  Thanks for the added functionality.  Consider this closed.
