### ISSUE TITLE
[Feature] Undo Function

### ISSUE THREAD

**Issue by b0mb** [ciur/papermerge#155]
It would be great implementingan undo function to papermerge.

especially when cutting documents something goes wrong very fast. ^^

**Comment by ciur** [comment]
Hi @b0mb,

thank you for opening this ticket. The "Undo" function contradicts versioning feature (or stated in other words - is a special case of versioning). Let's say a document Doc1 has 2 pages. If you cut/delete Doc1 second page - document's version will be incremented i.e. doc1 will have now version 2.

Now, question: if you click/choose "Undo" what should happen ? The usual undo feature like most of users are used to - should revert document to previous state - doest it mean reverting back to version 1 ?
Document management system usually rely on versioning. So, the "Undo feature" is exercised by "versioning" - what I mean, if you want to "Undo" you will need to revert to a previous version.

Versioning is not yet there, but it is something which I plan to implement. Because of argument I described above - I think "Undo Funcion" is just another name for "versioning" feature. 

@b0mb, what do you think ?

**Comment by b0mb** [comment]
Hi Eugen,

tanks for feedback. i don´t have a plan about versioning like you do i think but what i meant with undo is reverting back step by ystep like you can do in excel, word or photoshop. if this feature would be implemented with versioning that should be ok. ;)

**Comment by ciur** [comment]
As explained above - will be part of versioning feature. Versioning feature is mentioned as part of #79. 

Closing duplicate.
