### ISSUE TITLE
Slow increase in CPU usage over time

### ISSUE THREAD

**Issue by TheSpad** [ciur/papermerge#198]
**Description**
Brand new install with half a dozen documents uploaded, no automations in place, CPU usage slowly climbs over time without any changes being made.

**Expected**
CPU usage should not climb over time.

**Actual**
![image](https://user-images.githubusercontent.com/8425502/97360368-0308c700-1896-11eb-82ae-4241adbf30a9.png)

**Info:**
 - OS: Docker 19.03 on Ubuntu 20.04 LTS
 - Browser: N/A
-  Database: SQLite
 - Papermerge Version: 1.5

**Comment by ciur** [comment]
@TheSpad, really good catch!

I had this issue in production too, and to be honest, was very annoying :(

The problem is because of "default **file based** transport of messaging queue" which piles up files in **queue** folder (in project directory).
You have 2 options:
* regularly delete all files in **queue** folder (this folder is created automatically in same directory where manage.py file is).
* replace file based messaging transport with "in memory one" - e.g. redis.

For latter one, you need to replace following options:

```
CELERY_BROKER_URL = "filesystem://"
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'data_folder_in': PAPERMERGE_TASK_QUEUE_DIR,
    'data_folder_out': PAPERMERGE_TASK_QUEUE_DIR,
}
```
with this ones: 

```
CELERY_BROKER_URL = "redis://"
CELERY_BROKER_TRANSPORT_OPTIONS = {}
CELERY_RESULT_BACKEND = "redis://localhost/0"
```

**Comment by TheSpad** [comment]
Is there any risk of data loss from automating deletion of the queue files?

**Comment by ciur** [comment]
> Is there any risk of data loss from automating deletion of the queue files?

If data = your documents, then answer is **NO**. 

Files in queue directory they contain information about background jobs. If you delete them once a day (e.g. daily at 00:00) and in same time you start an OCR on document it might happen that you might delete that ocr job - means your document will not be OCRed because background job was accidentally deleted - **document itself won't be affected at all.**

My suggestion is to use redis (with configurations I gave above).
The "filesystem://" is good for small deployments (development env, testing, evaluation) because of its simplicity (no extra things to include).

**Comment by alex-phillips** [comment]
@ciur would it be safe to run something like a cron job that deletes anything in that folder older than a certain time? Or would that still run the risk of lost OCR jobs?

**Comment by ciur** [comment]
>  would it be safe to run something like a cron job that deletes anything in that folder older than a certain time?

@alex-phillips absolutely!
Deleting any file (in queue directory) older than 24 hours is safe - it will not affect any background job.

**Comment by maspiter** [comment]
Is Redis support still in development because I see django development configuration?

**Comment by amo13** [comment]
I don't see where to adjust to configuration to use redis. There is no `CELERY_BROKER_URL = "filesystem://"` in the `papermerge.conf.py` template configuration which I could replace with the redis.

**Comment by maspiter** [comment]
It is in base.py

**Comment by amo13** [comment]
I can find it in this repo, but I can't find it on my filesystem after after installation... maybe it is due to my packaging attempt on archlinux.
Can you please tell me the relative path of base.py to the papermerge install folder containing core, search, test on your system? Is it actually just `../config/settings/base.py?
Where is the file to be used defined and can I change its location?

**Comment by maspiter** [comment]
Could you elaborate what the problem is exactly?

The path is papermerge/config/settings and that is were it should be on install.

**Comment by amo13** [comment]
Ah, ok, now I have it and it seems to be working fine.
I install papermerge without virtual env and without pip but only with the package manager of arch linux. All dependencies are installed as individual packages which has the advantage of having them all updated together with system updates. 
Thanks for the help by the way :+1:

**Comment by amo13** [comment]
To my understanding, the suggested replacement of lines to use redis instead of filesystem would have to be repeated after every update, because the base.py file itself might get an update and would in turn replace the modified one from the previous version.
Is there a way to circumvent this?

**Comment by hactar** [comment]
So after having my papermerge instance running for a few months now, the cpu usage of an idle papermerge was at 97% - only after researching this I found this ticket. Information on this needs to be included in the documentation for docker, or even better, docker-compose/build needs to be adjusted to either use redis per default, or have a built in cronjob that deletes these files. Multiple people have already fallen into this hole, see issues referencing this one.

This needs a default docker fix please @ciur , I suggest reopening this issue.

**Comment by okoetter** [comment]
> This needs a default docker fix please @ciur , I suggest reopening this issue.

I second this. My CPU usage was >50% until I found this thread.

**Comment by ciur** [comment]
ok, guys, I reopened the issue and I will update documentation + update document files

**Comment by jorisvc** [comment]
> @TheSpad, really good catch!
> 
> I had this issue in production too, and to be honest, was very annoying :(
> 
> The problem is because of "default **file based** transport of messaging queue" which piles up files in **queue** folder (in project directory).
> You have 2 options:
> 
> * regularly delete all files in **queue** folder (this folder is created automatically in same directory where manage.py file is).
> * replace file based messaging transport with "in memory one" - e.g. redis.
> 
> For latter one, you need to replace following options:
> 
> ```
> CELERY_BROKER_URL = "filesystem://"
> CELERY_BROKER_TRANSPORT_OPTIONS = {
>     'data_folder_in': PAPERMERGE_TASK_QUEUE_DIR,
>     'data_folder_out': PAPERMERGE_TASK_QUEUE_DIR,
> }
> ```
> 
> with this ones:
> 
> ```
> CELERY_BROKER_URL = "redis://"
> CELERY_BROKER_TRANSPORT_OPTIONS = {}
> CELERY_RESULT_BACKEND = "redis://localhost/0"
> ```

Don't forget to install the REDIS server.
On Debian this is
```
apt install redis-server
systemctl start redis-server
systemctl status redis-server
```

Then restart your papermerge worker service.

**Comment by ciur** [comment]
I changed official docker compose file to use redis as message broker instead of filesystem based one.
Here [is the diff](https://github.com/ciur/papermerge/commit/968f37bfe75793e2563d7daaa46d45fb1d34e715).
Documentation update will follow...
