### ISSUE TITLE
Manual install - mglib issue

### ISSUE THREAD

**Issue by patrickomatik** [ciur/papermerge#20]
I've followed the steps in the docs for a manual install under ubuntu 18.04.2. All requirements.txt libs were satisfied correctly. When I run manage.py migrate, I get an error

` from mglib import step
ImportError: cannot import name 'step'`

I also get similar errors if I manage.py createsuperuser.

Doing an inspect on mglib in the python repl suggests that the library has no functions, which seems odd (but I am no python expert). Is pip pulling in the wrong mglib somehow?

**Comment by ciur** [comment]
You are absolutely right. Documentation tells you to clone master branch, which is incorrect. I updated docs with: 
```
   git clone **--branch v1.2.2** https://github.com/ciur/papermerge papermerge-proj
   git clone **--branch v1.2.2** https://github.com/ciur/papermerge-js
```
The error you saw, was because you tried to work in master branch, which is branch where daily commits goes into. 
[Here you can see an explanation of branch model I use in Papermerge DMS project.](https://papermerge.readthedocs.io/en/v1.2.2/developers_guide/branching.html).

**Comment by ciur** [comment]
I assume that document updates fixed the issue.
