### ISSUE TITLE
Automatically determine creation date via OCR

### ISSUE THREAD

**Issue by guillaume-u** [ciur/papermerge#205]
I would like to upload a lot of scan with different date formats. Ideally, as paperless, the _creation date_ (which is different than _added date_ for paperless) should be determined via OCR without setting the date format.

Is it a way to do that in the current version — I did not find this capability ? or can it be a new release ?

Thanks.

**Comment by ciur** [comment]
Hi @guillaume-u. In Papermerge there is only created_at field (creation date). One way to approach your problem would be to add "added date" metadata field.

**Comment by guillaume-u** [comment]
Thanks @ciur, just one more question, the created_at field is only depending on creation time (not the content of the doc), correct ?

**Comment by ciur** [comment]
@guillaume-u, correct, ``created_at`` field is set to the date your document was uploaded.
To be technically correct ``created_at`` is of so called datetime type (date + time), thus it store date and time when you document was uploaded to the Papermerge - and has nothing to do with content itself of the document.

**Comment by guillaume-u** [comment]
Thanks again @ciur.

Before closing this ticket, do you think this feature (add a date determined by OCR) is a good feature and can be added in the roadmap or not ?

**Comment by ciur** [comment]
it is definitely a good feature. Including "added date" sounds very reasonable. The problem with that, if someone else will requests a "sent date" (many physical letters include a field which indicate when that letter was sent) or maybe a "paid date" etc etc - it would be reasonable to include all those fields.
One solution would be to use metadata.
Yet another solution, which would be possible starting with [next release](https://github.com/ciur/papermerge/issues/203) is to add a very small app (I will document step by step how to do it) which will extend document model with whatever field date/integer field for your particular need/case. That would be as simple as:

```
class Document(AbstractDocument):
    """
    This is main document model extention which adds an extra date field
    """
    added_date = models.DateField(...)
```
Later approach has disadvantage that you need to know little bit of programming. But on the other hand, if your feature/add date field is really required I, or any other person can write a reusable app so that those who need _add date_ will include it in their Papermerge instance.

**Comment by guillaume-u** [comment]
Thanks !

As an ugly hack (for my usage only because it's not clean at all and it modified `created_at` instead of create a new attribute), I copy/past paperless regex into `core/automate.py`. It does the job for my import.

Thanks again for your project. As paperless it's a verry good one.

**Comment by amo13** [comment]
> As an ugly hack (for my usage only because it's not clean at all and it modifies `created_at` instead of creates a new attribute), I copy/past paperless regex into `core/automate.py`. It does the job for my import.

I also like a lot the idea of having automatic creation-date extraction. Would you mind sharing the regex from paperless here?
