### ISSUE TITLE
Easy export all documents data including metadata

### ISSUE THREAD

**Issue by ciur** [ciur/papermerge#23]
And eventually import back :)

**Comment by frenos** [comment]
I feel like this is a very important feature that would help a lot while papermerge is shaping up to be a fine product.
I know I would sleep better if I knew no matter what, I can just fire up an older docker container, restore the backup and be ready again in a few minutes.

Do you accept a PR request for this feature yet? If yes I would set up a descriptive PR with a plan of the MVP for this feature sometime on the weekend.

**Comment by ciur** [comment]
PR means Pull Request or Product Requirements ? :)
Obviously I welcome all suggestions !

**Comment by Tooa** [comment]
I would love to see the following use case considered when this feature is implemented:

**Given** the media folder as a host mount in my docker installation
**And** the media folder is already included in my rsync backup strategy 
**As a User**, I want to export/backup only the matching metadata
**so that** I can add the metadata to my existing rsync backup strategy

Feel free to reply in case the use case left any open questions.

**Comment by ciur** [comment]
Closed By [PR#33 ](https://github.com/ciur/papermerge/pull/33)
