### ISSUE TITLE
Calculate hash to prevent duplicates from being imported

### ISSUE THREAD

**Issue by croontje** [ciur/papermerge#263]
I was testing a little bit today, and I noticed that I can upload the same PDF over and over again.
I think it would be better if you would calculate a hash (eg MD5, SHA, ...) and on import check if it already exists.

It would be even better to detect 2 versions of the same document, but I think that's almost impossible...
For example if you scan the same document twice, flag them as duplicates. But as I said this seems almost impossible to me :)

**Comment by ciur** [comment]
@croontje, whether this feature is useful or not is a matter of debate (pros and cons).

There is a duplicate issue #167 on this topic.

For me personally, the inclusion of this feature as part of core will make _development mode_ more complex: many times while fixing bugs or just during development I use to upload 2-3 available to me document many times to "simulate" multitude of documents. With this hashing thingy I will need to adjust defaults.

Starting with Papermerge 2.0, you will be able to create a separate app (app == extention == plugin) which will provide this functionality. Actually I will create a hashing app as example of how to write external apps in order to extend core functionality.
