### ISSUE TITLE
Docker image for 1.3.0

### ISSUE THREAD

**Issue by sbonfert** [ciur/papermerge#32]
Paperless 1.3.0 was released some time ago. However, the provided docker images still seem to use 1.2.2 / 1.2.3.
Can you please update the docker image to 1.3.0?

**Comment by frenos** [comment]
Looking at the [tags](https://github.com/ciur/papermerge/tags)  1.2.3 was updated after 1.3 and is therefore newer/latest. Sadly there does not seem to be a docker container tagged with 1.3 as CI was introduced later.

**Comment by ciur** [comment]
I intentionally did not release docker image for version 1.3.0. 

Let me explain:
99% of changes in version 1.3.0 are internal refactoring. You can call this version "Developer friendly version". **There are no visible benefits for end user.** Version 1.3.0 introduces Metadata indeed - but only internal code is there (models, tests). UI for using UI is basically missing. I included only basic UI just to get a feeling how it is to work with newly added metadata API.

Because of above reason - I don't plan to release docker image for 1.3.0, again - unless you are developer working on Papermerge - you won't see any benefit.

Version 1.4.0 on the other hand - it is entirely user experience oriented. All new polished and shiny UI is there. It will include awesome (I really love it) UI to manage metadata.
**There will be docker image for version 1.4.0.**

Version 1.4.0, altogether with docker image - will be out in August (I am not sure which part of August though).

**Comment by sbonfert** [comment]
The release notes mention: "SQLite is default database (Postresql is now optional, available via Plugin)"
Therefore I wanted to skip the setup of a dedicated Postgres-container with version 1.3.
Am I getting something wrong here?

**Comment by ciur** [comment]
You are absolutely right - starting with Papermege 1.3.0 - Postgresql is optional.

But it is little bit more complicated than that.
First of all you will need to migrate your data from 1.2.0 to 1.3.0. And I still did not include documentation for that. Action item on me.

Next, Postgresql was used because of its [full text search ](https://www.postgresql.org/docs/12/textsearch.html)- which works fantastically well (it places better matches at the top of search results). If you get rid of postgres and use sqlite3 instead (provided by default since 1.3.0) -  **searching experience will drop.**. SQLite does not provide full text search benefits (it cannot weight which matches are better).

Also, important one, I did not create that plugin (that one to bring back fulll text search benefits of pg). Docker image which I plan to create will contain both postgresl dependency and yet to be created plugin.

I decided to include SQLite3 by default (instead of Postgresql) because it speeds up initial development setup. As I told you in previous comment - version 1.3.0 is developer friendly :).

**Comment by frenos** [comment]
To give you feedback as a developer: Instead of having the sqlite feature, your /docker folder with the docker-composes was a lot more helpful. With that I was up to speed in 15min and was able to start exploring the code.
I mount my code into the container and have a shell there. I think with pycharm you can also use the gui debugger connecting into a container but I haven't tried it.

**Comment by sbonfert** [comment]
What would you recommend for someone doing a fresh start now?
Should I set up papermerge 1.2.3 with postgres? Would I have to transition to sqlite with 1.4?
Or would you rather recommend to wait for 1.4?

**Comment by ciur** [comment]
@frenos 
> To give you feedback as a developer: Instead of having the sqlite feature, your /docker folder with the docker-composes was a lot more helpful. With that I was up to speed in 15min and was able to start exploring the code.
> I mount my code into the container and have a shell there. I think with pycharm you can also use the gui debugger connecting into a container but I haven't tried it.

Here is a test for the efficiency of project X initial setup / how easy to to start dev environment for project X:
 
On new computer (with newly installed OS) a URL to open source project X is provided.
How much time you need to fix a bug/start project X on your new computer (1. install git, 2. clone repo 3. ... etc etc) ?

Answer to above question triggered all changes from release 1.3.0.
The fact that a project is easy to setup with docker - does not mean at all that project is simple to setup (or it is has overly complex initial setup).

**Comment by ciur** [comment]
@sbonfert 
> What would you recommend for someone doing a fresh start now?
> Should I set up papermerge 1.2.3 with postgres? Would I have to transition to sqlite with 1.4?
> Or would you rather recommend to wait for 1.4?
 
I would recommend to wait for 1.4 I will release an alpha version (+docker image) in less than a month. This way you will avoid frustration of migration process.

**Comment by sbonfert** [comment]
Alright, then that is what I will do.
Thank you for your explanations and your suggestion.

**Comment by okoetter** [comment]
Can anybody tell me how to setup a new 1.4.x installation with Docker using only sqlite and not Postgres? Is there another docker compose file or do I have to make some changes to the existing docker compose file?
