### ISSUE TITLE
Docker: add REDIS_HOST and REDIS_PORT variables 

### ISSUE THREAD

**Issue by matejdro** [ciur/papermerge#407]
I want to use papermerge images, but I do not want to use papermerge's docker compose (I want to use one postgres and one redis instance for all my services instead of every service setting up their own).

This worked with the postgres (papermerge thankfully provides environment variables for setting that), but It appears that currently redis is hardcoded to always connect to the `redis` hostname. From what I can see, this breaks the worker (it does not startup without redis).

Please add a way to setup worker without redis (I'm using this personally, so there is no need for big caching on my side) or to change redis hostname, so I can use existing redis server.

**Comment by matejdro** [comment]
In the meantime I'm using docker image from linuxserver: https://github.com/linuxserver/docker-papermerge. This image is standalone and provides all of above options.

**Comment by stavros-k** [comment]
those vars will also help in deploying it on kubernetes!

**Comment by ciur** [comment]
Available since [2.1.0a35](https://github.com/papermerge/papermerge-core/pkgs/container/papermerge/30997992?tag=2.1.0a35).

Here is [docker compose file example](https://github.com/papermerge/papermerge-core/blob/master/docker/docker-compose.yml) (redis configuration is passed via ``PAPERMERGE__REDIS__HOST``, ``PAPERMERGE__REDIS__PORT``, notice double underscores).

And here is relevant [documentation](https://docs.papermerge.io/Settings/redis.html)

**Comment by AeliusSaionji** [comment]
There seems to have been a regression on this - I cannot get it to work.

Ah, the issue was I used this unloved file https://github.com/ciur/papermerge/blob/master/docker/docker-compose.yml
