### ISSUE TITLE
Home navigation causes web to refresh

### ISSUE THREAD

**Issue by ajarzyn** [ciur/papermerge#436]
**Description**
1. All action involved changing tabs (Documents, Inbox, Automates etc...)
2. Home on top left navigation bar

Causes whole app to refresh.

**Expected**
No refresh of the web (loosing focus of what user was actually doing).

**Actual**
Navigation though lower level folders is handled well.

Example directory structure:
- Home
    - nvm
    - parent
        - child

Navigating from child to parent - no refresh
Navigating from parent to child - no refresh
Navigating from any point to Home - refresh

**Info:**
 - OS: Ubuntu 18
 - Browser Firefox 95.0 (64-bit)
 - Papermerge Version 2.0 

**Additional info**
Using this occasion I would like to notice that there is no `..` button to navigate to parent directory. Which would be a nice feature (if you would like me to create another issue - feature request - for this let me know).

**Comment by ciur** [comment]
@ajarzyn thank you for opening this bug. This problem actually "was fixed " in upcoming 2.1 release. I recorded [a short screencast](https://www.youtube.com/watch?v=rh6p48W4wXk&t=278s) which demos exactly this part (no reloads).

"was fixed" is in quotes because the I rewrote the whole frontend in [emberjs](https://emberjs.com/) - which is a frontend framework with reactive pattern - which basically takes care exactly of the problem you described - the whole  frontend application is a single web app and it works without reloads.

I will keep this bug open until release 2.1 will be out.
About `..` button is actually a good idea. If you like you can open a separate bug for that issue, I will gladly add that feature to next release.

The source code for new, reactive pattern based frontend, [is here](https://github.com/papermerge/papermerge.js). Notice there are no release tags or whatsoever - as  I started working on it in September.

**Comment by ajarzyn** [comment]
Thank you for showing me the video. 2.1 really looks grate can't wait to test it already.

I've created #437 for `..` feature (I do not think it's a bug).

I've looked into history, and your activity stream, you are busy man. I do not know how you find the time for all of that.

Best of luck to you.

**Comment by ciur** [comment]
Feature is available in [2.1.0a35](https://github.com/papermerge/papermerge-core/pkgs/container/papermerge/30997992?tag=2.1.0a35).
Basically now frontend (i.e. user web interface) is implemented as "single page application" and it "does not reload whole content again" while nagivating.

Here is a quick demo:
![single-page-application](https://user-images.githubusercontent.com/24827601/182027729-59af42aa-e892-43d7-a941-499154311cdb.gif)
