### ISSUE TITLE
config file on docker 

### ISSUE THREAD

**Issue by Aruscha** [ciur/papermerge#51]
Hello,

I would like to follow these instructions
(https://papermerge.readthedocs.io/en/latest/settings.html#Email)
Import my mails, unfortunately I don't know where in docker compose the config for this is, or I can't find it, can someone help me?

**Comment by ciur** [comment]
Hi @Aruscha,

thank you for giving papermerge a try!

Those settings you are trying to follow are for latest version (1.4) - which is still in development (well, last phase, testing, QA, bug fixes). If you want to try them, [use this installation steps.](https://papermerge.readthedocs.io/en/latest/setup/manual_way.html).
Notice that you need to run [a flavour of linux machine or MacOS with at least python 3.7.](https://papermerge.readthedocs.io/en/latest/requirements.html)

I will provide in a week a docker image for 1.4.rc1 (release candidate 1) so that you can start using 1.4 directly from docker.

**Comment by Aruscha** [comment]
If the email settings don't work yet I'll wait until the new version is released thanks :)

**Comment by Aruscha** [comment]
I open this again and have followed your instructions and made the email settings but nothing is uploaded...![Screenshot_20200804-231200646.jpg](https://user-images.githubusercontent.com/49562390/89345609-05e58880-d6a8-11ea-8775-d2a49b7b633c.jpg)
