### ISSUE TITLE
1.4.0rc1 .jpg files shows broken img icon

### ISSUE THREAD

**Issue by tkammerlander** [ciur/papermerge#53]
Hy @ciur 

just cloned the new release and started up docker. unfortunately the .jpg bug is still there
![image](https://user-images.githubusercontent.com/1456877/89337918-09731280-d69c-11ea-9deb-7d4648788641.png)

regards tom

**Comment by ciur** [comment]
Hi @tkammerlander 

this is because I messed up the docker image. Application-wise (I mean papermerge code) it works. 

Try [online demo](https://demo.papermerge.com).  Upload an jpeg (jpg) as test. Credentials are guest/password77
As test for online demo I added a folder titled - jpeg (readonly) where I uploaded an jpeg image. 

I will fix docker image today and provide an rc2.

Thank you for your quick feedback, @tkammerlander, I highly appreciate it!

**Comment by ciur** [comment]
Jetzt muss es aber funktionieren!

I fixed docker image and pushed new one - tagged 1.4.0.rc2. Could you please retest it?
Just to make sure that you have right image, delete any reference to 1.4.0.rc1 first.
With docker, you can:
```
  docker image ls
```
to see docker images.  Then copy IMAGE ID tagged with 1.4.0.rc1 and:

```
  docker image rm  <image_id> -f
```
This will forcefully delete previous docker images. Afterwords:
```
1. git pull  # to take latest changes... you know, just in case
2. cd docker/1.4/
3. docker-compose up
```

**Comment by tkammerlander** [comment]
cool thanks a lot for fixing it that fast. ill test everything tonight when iam back home from work 👍

**Comment by tkammerlander** [comment]
![image](https://user-images.githubusercontent.com/1456877/89449250-1ace2480-d759-11ea-9331-19bb242302b9.png)
cool cool, works like a charm, we can close this issue :-).

thanks for the ultra fast fix and response. even our paid enterprise software vendors dont react that fast :-).
always nice to know that as a potential customer :-) wish u all the best with the project.

regards, thomas

**Comment by ciur** [comment]
Thank you !
