### ISSUE TITLE
Configfile on 1.4.0rc4

### ISSUE THREAD

**Issue by Aruscha** [ciur/papermerge#56]
Howdy,

I have now installed the Rc4 and everything works except the import folder and the email import function, see the screenshot of my config, what did I do wrong?

![IMG_20200805_183412_463.jpg](https://user-images.githubusercontent.com/49562390/89439350-5ad9db00-d74a-11ea-87c1-d05e3e0294a9.jpg)

**Comment by ciur** [comment]
Your configuration file is correct. Application should work.

One thing that crosses my mind is - problem might be that application from inside docker container is unable to connect to outside world (thus fetch your email).
I will test it with my own imap/email account and come back with details.

Danke für den Feedback!

**Comment by ciur** [comment]
Fixed.
First -  you will need to pull latest code (built inside 1.4.0.rc3 docker image).
Then one very important point, which I failed to mention in documentation  - you need to change MAIL related and IMPORTER_DIR configurations inside worker container.
This is because worker is the one who fetches your email or imports folders - not main app.

I will update documentation with this important point.
Thank you for bringing it up!
