### ISSUE TITLE
Unable to change language on containerized install (Docker)

### ISSUE THREAD

**Issue by gururise** [ciur/papermerge#68]
Used the docker install and after everything was done, only two languages (DEUTSCH and SPANISCH) were available in the web front end for the OCR. **I am unable to select ENGLISH as a OCR language.** I had to open a bash shell to the papermerge_worker container to get to the settings which I found in /opt/app.

The **papermerge.conf.py** file defaults to these settings:
```
OCR_DEFAULT_LANGUAGE = "deu"

OCR_LANGUAGES = {
    "deu": "Deutsch",
    "spa": "Spanish",
}
```

I changed them to the following and restarted all the containers:

```
OCR_DEFAULT_LANGUAGE = "eng"

OCR_LANGUAGES = {
    "deu": "Deutsch",
    "eng": "English",
}
```

However, I still only see German and Spanish as language options for the OCR.  How can one change the language of the OCR in a docker install?

**Comment by ciur** [comment]
I understand what you mean. There is a confusion - it is because I failed to mention one important aspect in documentation :grin: . 
There is worker and main app. And the thing is that some configurations apply only to worker, some only to main app, and some to both!

OCR_LANGUAGES and OCR_DEFAULT_LANGUAGE apply to both - worker and main app.

In your case - you just need change configuration file on both instances - **worker and main app.**
You did it correctly, but you changed papermerge.con.py only on worker.

I will label this issue as documentation bug.

Thank you for great feedback!

**Comment by ciur** [comment]
I updated documentation.
Have a look at [settings](https://papermerge.readthedocs.io/en/latest/settings.html#main-app-worker-or-both) and [docker setup](https://papermerge.readthedocs.io/en/latest/setup/docker.html#main-app-worker-or-both).
Now each configuration setting has a context: ``main app`` or ``worker`` or ``main app, worker``. Depending on the context that configuration needs to be changed on main app, worker or on both.
