### ISSUE TITLE
Question concerning OCR_LANGUAGES setting

### ISSUE THREAD

**Issue by mtonnie** [ciur/papermerge#69]
As far as I understood these setting will define which languages are supported from tesseract and the value is displayed in gui.
The consequence is, that the language in gui won't be translated e.g. Deutsch => German => Allemand.

For the values, usually this should contain a filtered list of all languages tesseract will support, that mean a list of installed tessdata files.

What about the idea to get the list of installed languages from tesseract, filter it if necessary and to map the language names with an dictionary which can be translated? 

` /usr/local/bin/tesseract --list-langs | sed -n '1!p'`

**Comment by ciur** [comment]
Hi @mtonnie,

your suggestion makes perfect sense and I understand your point.
In most of production environments though, tesseract is installed only on worker part.  The built-in worker (the one you start with ./manage.py worker) is there for convenience only. Built-in worker simplifies initial development environment and it is really good for simple one host deployments.

However, it is good to think always[ about worker(s) as separate machine/host](https://papermerge.readthedocs.io/en/latest/developers_guide/design.html). With that being said - gui **usually** has no access to /usr/local/bin/tesseractact + language data. This is the reason OCR_LANGUAGES settings was introduced.

Also, today[ I updated documentation to include "context"](https://papermerge.readthedocs.io/en/latest/settings.html#main-app-worker-or-both) for each configuration setting:

![context-added-today](https://user-images.githubusercontent.com/24827601/90314326-1d780900-df13-11ea-99ed-668c22e27c32.png)

Even though OCR_LANGUAGES is listed as applicable to both main app and worker, as of writing this line I am thinking to correct it again with context: main app only - because only main app profits from this option and worker actually does not use it at all.

**Comment by ciur** [comment]
Ah, I am sorry, I did forgot to comment on this line:

> The consequence is, that the language in gui won't be translated e.g. Deutsch => German => Allemand.

It should be translated! If not, that is a translation issue/bug. What matter for application is the 3 letters code (eng, deu, spa, fra...)

**Comment by mtonnie** [comment]
Thanks for the explanation, makes definitely sense.
I'm completely focus on Synology packaging topic and haven't though about separated app and worker.
