### ISSUE TITLE
Download document with OCRed layer of text.

### ISSUE THREAD

**Issue by ciur** [ciur/papermerge#78]
One of the [features suggested in this discussion ](https://www.reddit.com/r/selfhosted/comments/ibwuj2/papermerge_14_out/)
is ability to download document with OCRed layer of text.

If I think carefully of my workflow - I needed to download many times the documents, and even though OCR text layer was available in document viewer - downloaded PDF version did not contained that text.

I think it makes sense to add make download button as dropdown with 2 versions:
* download original
* download original with text over (or embedded text)

Here is [comment where user mentioned this](https://www.reddit.com/r/selfhosted/comments/ibwuj2/papermerge_14_out/g1yqlsy?utm_source=share&utm_medium=web2x).

**Comment by ciur** [comment]
Great, feature request, Eugen !

**Comment by ciur** [comment]
Sure, Eugen, you are welcome! :+1: 
 I love speaking to myself... :unamused:

**Comment by Quotic** [comment]
Eugen, I agree with Eugen. That will be great.

**Comment by ciur** [comment]
[Feedback from reddit](https://www.reddit.com/r/selfhosted/comments/jb3jcl/papermerge_15_is_out_finally_with_tags/g8t5n5u?utm_source=share&utm_medium=web2x&context=3)

> Hi there. If the feature doesn't currently exist to 'embed' the OCR/plain-text into the document itself, please consider it as a feature request.
> 
> Acrobat Pro and ocrmypdf both do this, but many tools do not, and instead just put the plan text data in a database file rather than inline within the document. This means if you ever take your pdf somewhere else, you have to OCR it again.

**Comment by ebertland** [comment]
I would like this to work as part of a backup to cloud strategy as well. When I copy the PDF files to a cloud service, I would like them to be searchable there as well. (My current workaround is to run the scans through ocrmypdf before sending them to papermerge.)

When you implement this feature, please consider providing the same capability through a REST API also, so that I can make a custom backup utility. Thanks!

**Comment by CorneliousJD** [comment]
I would also like this to be implemented.

Right now in order to make this happen I'm also running PDFs through OCRmyPDF-Auto (docker container) to automatically de-skew the pages and embed OCR directly into PDF before importing into Papermerge, that way the raw PDF file on the filesystem retains embedded OCR, AND its hilightable within the webUI of Papermerge as well. Best of both worlds.

Not needing to do this step first would make the process even faster for usres like me and @ebertland 

If it's a toggle-able option within Papermerge that would be even better, as some people may not need it, but I think defaulting to ON would be the best. 

May even be a good idea to have a button to go back and re-encode the PDFs that already exist within Papermerge so they get OCR data embedded directly into the PDF, that way our existing libraries are already covered as well.

Until then though I will continue to first run PDFs through OCRmyPDF-auto before ingesting into Papermerge.

Thanks for the consideration!

**Comment by ciur** [comment]
Feature is implemented and it is now in develop branch. Will be released as part of version 2.1.
With this feature in place, when user uploads a new document, after OCR process is complete, user can download 2 document versions - so called document version 0 (v0) - original (i.e. exactly same as uploaded) and version 1 (v1) the document with text overlay i.e. fully searchable PDF document.
Text overlay is created using [OCRmyPDF](https://github.com/jbarlow83/OCRmyPDF) .

**Comment by ciur** [comment]
Text overlay feature is implemented and available in [2.1.0a35](https://github.com/papermerge/papermerge-core/pkgs/container/papermerge/30997992?tag=2.1.0a35).

Here is a quick demo:
![text-overlay-demo](https://user-images.githubusercontent.com/24827601/182030285-cd4cf63b-4fe6-4d35-a6da-7d6593a5f422.gif)

[Documentation](https://docs.papermerge.io/User%27s%20Manual/ocr.html#ocred-text-layer)
